export interface ProposalEstimateData {
  provider: 'aws' | 'azure' | 'gcp';
  providerLabel: string;
  region: string;
  monthlyCost: number;
  annualCost: number;
  oneYearRiMonthlyCost: number;
  threeYearRiMonthlyCost: number;
  confidence: string;
  lineItemsCount: number;
  lineItems: Array<{
    category: string;
    serviceName: string;
    skuName: string;
    monthlyCost: number;
    assumption: string;
  }>;
  assumptions: string[];
}

export interface ProposalInput {
  title?: string;
  clientName?: string;
  preparedBy?: string;
  date?: string;
  requirementsSummary: string;
  estimates: ProposalEstimateData[];
}

export class ProposalGenerator {
  static generateMarkdownProposal(input: ProposalInput): string {
    const title = input.title ?? 'Multi-Cloud Infrastructure Cost & Proposal Review';
    const clientName = input.clientName ?? 'Valued Client';
    const preparedBy = input.preparedBy ?? 'Cloud Solutions Architect';
    const date = input.date ?? new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const sortedEstimates = [...input.estimates].sort((a, b) => a.monthlyCost - b.monthlyCost);
    const recommended = sortedEstimates[0];

    let md = `# ${title}\n\n`;
    md += `**Client**: ${clientName}  \n`;
    md += `**Prepared By**: ${preparedBy}  \n`;
    md += `**Date**: ${date}  \n\n`;

    md += `---\n\n`;
    md += `## 1. Executive Summary\n\n`;
    md += `This proposal provides a cross-cloud cost comparison (AWS, Azure, GCP) based on the specified infrastructure requirements:\n\n`;
    md += `> **Requirements Summary**: ${input.requirementsSummary}\n\n`;

    if (recommended) {
      md += `Based on public list-price pricing analysis, **${recommended.providerLabel}** offers the most cost-effective On-Demand baseline at **$${recommended.monthlyCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} / month** ($${recommended.annualCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} / year).\n\n`;
    }

    md += `## 2. Multi-Cloud Monthly & Annual Cost Comparison\n\n`;
    md += `| Provider | Region | On-Demand (Monthly) | On-Demand (Annual) | 1-Yr Savings Plan (Est. -30%) | 3-Yr Savings Plan (Est. -50%) |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;

    for (const est of input.estimates) {
      const isRec = recommended && est.provider === recommended.provider;
      const providerStr = isRec ? `**${est.providerLabel} (Recommended)**` : est.providerLabel;
      md += `| ${providerStr} | ${est.region} | $${est.monthlyCost.toFixed(2)} | $${est.annualCost.toFixed(2)} | $${est.oneYearRiMonthlyCost.toFixed(2)}/mo | $${est.threeYearRiMonthlyCost.toFixed(2)}/mo |\n`;
    }

    md += `\n*Note: Reserved Instance and Savings Plan estimates apply benchmark discount factors (30% for 1-Yr, 50% for 3-Yr) against base compute and database workloads.*\n\n`;

    md += `## 3. 3-Year Total Cost of Ownership (TCO) Projection\n\n`;
    md += `| Provider | 3-Yr On-Demand TCO | 3-Yr Committed Savings Plan TCO | Potential 3-Yr Savings |\n`;
    md += `| :--- | :--- | :--- | :--- |\n`;

    for (const est of input.estimates) {
      const onDemandTco = est.annualCost * 3;
      const committedTco = est.threeYearRiMonthlyCost * 12 * 3;
      const savings = onDemandTco - committedTco;
      md += `| ${est.providerLabel} | $${onDemandTco.toFixed(2)} | $${committedTco.toFixed(2)} | **$${savings.toFixed(2)}** |\n`;
    }

    md += `\n## 4. Provider Line-Item Breakdown\n\n`;

    for (const est of input.estimates) {
      md += `### ${est.providerLabel} Breakdown (${est.region})\n\n`;
      md += `| Category | Service Name | SKU / Description | Monthly Cost |\n`;
      md += `| :--- | :--- | :--- | :--- |\n`;

      for (const item of est.lineItems) {
        md += `| ${item.category} | ${item.serviceName} | ${item.skuName} | $${item.monthlyCost.toFixed(2)} |\n`;
      }
      md += `| **Total** | | | **$${est.monthlyCost.toFixed(2)}** |\n\n`;

      if (est.assumptions.length > 0) {
        md += `**Key Pricing Assumptions & Exclusions (${est.providerLabel})**:\n`;
        for (const asm of est.assumptions) {
          md += `- ${asm}\n`;
        }
        md += `\n`;
      }
    }

    md += `## 5. Architectural & Decision Guidelines\n\n`;
    md += `1. **Workload Placement**: Compare regional availability and native service parity before committing to a single cloud.\n`;
    md += `2. **Discount Strategies**: Leverage 1-Year or 3-Year Savings Plans / Reserved Instances for persistent core compute and databases.\n`;
    md += `3. **Egress & Storage Costs**: Monitor data transfer out and log retention policies to prevent budget overruns.\n\n`;
    md += `---\n*Generated by Multi-Cloud Cost Calculator Engine*\n`;

    return md;
  }

  static generateHtmlProposal(input: ProposalInput): string {
    const title = input.title ?? 'Multi-Cloud Infrastructure Cost Proposal';
    const clientName = input.clientName ?? 'Valued Client';
    const preparedBy = input.preparedBy ?? 'Cloud Solutions Architect';
    const date = input.date ?? new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const sortedEstimates = [...input.estimates].sort((a, b) => a.monthlyCost - b.monthlyCost);
    const recommended = sortedEstimates[0];

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1e293b; line-height: 1.5; padding: 40px; max-width: 900px; margin: 0 auto; }
    h1 { color: #0f172a; font-size: 26px; border-bottom: 2px solid #0284c7; padding-bottom: 12px; }
    h2 { color: #1e293b; font-size: 18px; margin-top: 28px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
    h3 { color: #334155; font-size: 15px; margin-top: 20px; }
    .meta { background: #f8fafc; border: 1px solid #e2e8f0; padding: 12px 16px; border-radius: 8px; font-size: 13px; margin-bottom: 24px; }
    .meta p { margin: 4px 0; }
    .summary-box { background: #f0f9ff; border-left: 4px solid #0284c7; padding: 12px 16px; margin: 20px 0; font-size: 13px; border-radius: 0 8px 8px 0; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12px; }
    th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
    th { background: #0f172a; color: #ffffff; font-weight: 600; }
    tr:nth-child(even) { background: #f8fafc; }
    .total-row { font-weight: bold; background: #e2e8f0 !important; }
    .recommended-tag { background: #dcfce7; color: #166534; font-weight: bold; padding: 2px 6px; border-radius: 4px; font-size: 11px; }
    .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 11px; color: #64748b; text-align: center; }
    @media print { body { padding: 0; max-width: 100%; } .no-print { display: none; } }
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom: 20px; text-align: right;">
    <button onclick="window.print()" style="background: #0284c7; color: white; border: none; padding: 10px 18px; font-size: 14px; font-weight: bold; border-radius: 6px; cursor: pointer;">🖨️ Print / Save as PDF</button>
  </div>

  <h1>${title}</h1>
  <div class="meta">
    <p><strong>Client:</strong> ${clientName}</p>
    <p><strong>Prepared By:</strong> ${preparedBy}</p>
    <p><strong>Date:</strong> ${date}</p>
  </div>

  <h2>1. Executive Summary</h2>
  <div class="summary-box">
    <strong>Requirements Summary:</strong> ${input.requirementsSummary}
  </div>
  ${recommended ? `<p>Based on public list-price pricing analysis, <strong>${recommended.providerLabel}</strong> offers the most cost-effective On-Demand baseline at <strong>$${recommended.monthlyCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} / month</strong> ($${recommended.annualCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} / year).</p>` : ''}

  <h2>2. Multi-Cloud Monthly & Annual Cost Comparison</h2>
  <table>
    <thead>
      <tr>
        <th>Provider</th>
        <th>Region</th>
        <th>On-Demand (Monthly)</th>
        <th>On-Demand (Annual)</th>
        <th>1-Yr Savings Plan</th>
        <th>3-Yr Savings Plan</th>
      </tr>
    </thead>
    <tbody>
      ${input.estimates.map((est) => {
        const isRec = recommended && est.provider === recommended.provider;
        return `<tr>
          <td><strong>${est.providerLabel}</strong> ${isRec ? '<span class="recommended-tag">Recommended</span>' : ''}</td>
          <td>${est.region}</td>
          <td>$${est.monthlyCost.toFixed(2)}</td>
          <td>$${est.annualCost.toFixed(2)}</td>
          <td>$${est.oneYearRiMonthlyCost.toFixed(2)}/mo</td>
          <td>$${est.threeYearRiMonthlyCost.toFixed(2)}/mo</td>
        </tr>`;
      }).join('')}
    </tbody>
  </table>

  <h2>3. 3-Year Total Cost of Ownership (TCO) Projection</h2>
  <table>
    <thead>
      <tr>
        <th>Provider</th>
        <th>3-Yr On-Demand TCO</th>
        <th>3-Yr Committed Savings Plan TCO</th>
        <th>Potential 3-Yr Savings</th>
      </tr>
    </thead>
    <tbody>
      ${input.estimates.map((est) => {
        const onDemandTco = est.annualCost * 3;
        const committedTco = est.threeYearRiMonthlyCost * 12 * 3;
        const savings = onDemandTco - committedTco;
        return `<tr>
          <td><strong>${est.providerLabel}</strong></td>
          <td>$${onDemandTco.toFixed(2)}</td>
          <td>$${committedTco.toFixed(2)}</td>
          <td><strong>$${savings.toFixed(2)}</strong></td>
        </tr>`;
      }).join('')}
    </tbody>
  </table>

  <h2>4. Provider Line-Item Breakdown</h2>
  ${input.estimates.map((est) => `
    <h3>${est.providerLabel} (${est.region})</h3>
    <table>
      <thead>
        <tr>
          <th>Category</th>
          <th>Service Name</th>
          <th>SKU / Description</th>
          <th>Monthly Cost</th>
        </tr>
      </thead>
      <tbody>
        ${est.lineItems.map((item) => `
          <tr>
            <td>${item.category}</td>
            <td>${item.serviceName}</td>
            <td>${item.skuName}</td>
            <td>$${item.monthlyCost.toFixed(2)}</td>
          </tr>
        `).join('')}
        <tr class="total-row">
          <td colspan="3"><strong>Total (${est.providerLabel})</strong></td>
          <td><strong>$${est.monthlyCost.toFixed(2)}</strong></td>
        </tr>
      </tbody>
    </table>
  `).join('')}

  <div class="footer">
    Generated by Multi-Cloud Cost Calculator Engine • ${date}
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 400);
    };
  </script>
</body>
</html>`;
  }
}
